### PR TITLE
update import path for pbkdf2

### PR DESCRIPTION
**Pull request by AnatoliiD**

### CODE REVIEW

**Comment by andrewslotin** [comment]
Thank you!

**Comment by andrewslotin** [comment]
@railsme, could you also update the package name in .travis.yml?

**Comment by AnatoliiD** [comment]
@andrewslotin done! maybe we should add more Go versions to travis? 😄

**Comment by andrewslotin** [comment]
@railsme, this is a great idea, this project got a bit outdated 😃

**Pull request merged**
